### ISSUE TITLE
Initial flag asset by country code

### ISSUE THREAD

**Issue by ricardonior29** [dev-naiksan/country-calling-code-picker#1]
I send the callingCode and countryCode to a server (not the flag). But when i want to build the form again and paint the flag with the server response, i just have the country code.

So, please change the name of the flags (example "US.png"). This way I can match the countryCode with the flag route (asset)

Thanks

**Comment by dev-naiksan** [comment]
Hello @ricardonior29 please use below method. I have added the same in readme now.
`Country country = await getCountryByCountryCode(context, 'US');`
Alternatively you can retrieve all the countries using 
`getCountries(context);`

**Comment by zooRg** [comment]
if use method getCountries and use path for image 
```
Image.asset(
  'packages/country_calling_code_picker/' + countries.first.flag,
),
```
