### ISSUE TITLE
getDefaultCountry doesn't respond with valid country on iPhone

### ISSUE THREAD

**Issue by margorski** [dev-naiksan/country-calling-code-picker#5]
Hello, 
In our app, by calling the getDefaultCountry function from the package on Android we get a valid country based on a SIM card and for iOS, we always get Afghanistan which is the first country on the list.

After investigation, I found an error in the getDefaultCountry function.

functions.dart:24
`final countryCode = await FlutterSimCountryCode.simCountryCode;`
above function responds with country code in lowercase on iOS.

And the list of countries in line 21 has set value `countryCode` upper cased.
Searching for a valid country in lines 25-26 fails because of the inconsistent casing.

Simple .toLowerCase in line 26 would fix that to have casing consistency.

**Comment by dev-naiksan** [comment]
Thanks for this. I will look into it and get back asap.

**Comment by dev-naiksan** [comment]
@margorski Can you please check if this PR fixes your issue?

**Comment by margorski** [comment]
Wow, you are lightspeed. Yes, that fix my issue.

**Comment by dev-naiksan** [comment]
Thanks! Cool, will merge and make a release then
